(("default" . ((user-emacs-directory . "C:\\Git\\grimoire\\custom.emacs.d"))))
("doom" . ((user-emacs-directory .  "C:\\Git\\grimoire\\+doom\\doom.emacs.d")
           (env . (("DOOMDIR" .   "C:\\Git\\grimoire\\+doom\\doom.dir")))))
(("spacemacs" . ((user-emacs-directory . "C:\\Git\\grimoire\\+spacemacs\\spacemacs.emacs.d")))
(("magic" . ((user-emacs-directory . "C:\\Git\\grimoire\\custom.emacs.d"))))
