(("default" . ((user-emacs-directory . "C:\\Git\\grimoire\\files\\emacs\\custom.emacs.d")))
("doom" . ((user-emacs-directory .  "C:\\Git\\grimoire\\files\\emacs\\doom\\doom.emacs.d")
           (env . (("DOOMDIR" .   "C:\\Git\\grimoire\\files\\emacs\\doom\\doom.dir")))))
("spacemacs" . ((user-emacs-directory . "C:\\Git\\grimoire\\files\\emacs\\spacemacs\\spacemacs.emacs.d")))
("magic" . ((user-emacs-directory . "C:\\Git\\grimoire\\files\\emacs\\custom.emacs.d"))))
