#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

# Following line was automatically added by arttime installer
export PATH=/home/wych/.local/bin:$PATH
exec zsh
