[starship.files]
"files/starship.toml" = "~/.config/starship.toml"

[nushell.files]
"files/config.nu" = "~/.config/nushell/config.nu"
"files/env.nu" = "~/.config/nushell/env.nu"

[elvish.files]
"files/rc.elv" = "~/.config/elvish/rc.elv"

[lvim.files]
"files/lvim.lua" = "~/.config/lvim/config.lua"

[nvim.files]
"files/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[zsh.files]
"files/zshrc" = "~/.zshrc"

[bash.files]
"files/bashrc" = "~/.bashrc"

[wezterm.files]
"files/wezterm.lua" = "C:\\Users\\Blue\\.config\\wezterm\\wezterm.lua"
[wezterm.variables]
font = "FantasqueSansMono NF"
font_size = 16.0
zenmode_font_size = 40.0
shell = "Powershell"
directory = "None"

[qutebrowser.files]
"files/qutebrowser" = { target = "C:\\Users\\lumin\\AppData\\Roaming\\qutebrowser\\config", type = "symbolic", recurse = false }

[emacs.files]
"files/emacs/emacs.d" = { target = "C:\\Users\\lumin\\.emacs.d", type = "symbolic", recurse = false }
"files/emacs/emacs-profiles.el" = "C:\\Users\\lumin\\.emacs-profiles.el"

[keypirinha.files]
"files/keypirinha/portable.ini" = "C:\\Users\\Blue\\scoop\\apps\\keypirinha\\current\\portable.ini"
