[starship.files]
"files/starship.toml" = "~/.config/starship.toml"

[nushell.files]
"files/config.nu" = "~/.config/nushell/config.nu"
"files/env.nu" = "~/.config/nushell/env.nu"

[lvim.files]
"files/lvim.lua" = "~/.config/lvim/config.lua"

[nvim.files]
"files/nvim" = {target="~/.config/nvim", type="symbolic", recurse=false}

[alacritty.files]
"files/alacritty.yml" = "C:\\Users\\Blue\\AppData\\Roaming\\alacritty\\alacritty.yml"
[alacritty.variables]
shell = "Powershell"
directory = "None"
