[starship.files]
"files/starship.toml" = "~/.config/starship.toml"

[nushell.files]
"files/config.nu" = "~/.config/nushell/config.nu"
"files/env.nu" = "~/.config/nushell/env.nu"

[lvim.files]
"files/lvim.lua" = "~/.config/lvim/config.lua"
