[starship.files]
"files/starship.toml" = "~/.config/starship.toml"

[nushell.files]
"files/config.nu" = "~/.config/nushell/config.nu"
"files/env.nu" = "~/.config/nushell/env.nu"

[elvish.files]
"files/rc.elv" = "~/.config/elvish/rc.elv"

[lvim.files]
"files/lvim.lua" = "~/.config/lvim/config.lua"

[nvim.files]
"files/nvim" = {target="~/.config/nvim", type="symbolic", recurse=false}

[wezterm.files]
"files/wezterm.lua" = "C:\\Users\\Blue\\.config\\wezterm\\wezterm.lua"
[wezterm.variables]
shell = "Powershell"
directory = "None"
