[starship.files]
"files/starship.toml" = "~/.config/starship.toml"

[nushell.files]
"files/config.nu" = "~/.config/nushell/config.nu"
"files/env.nu" = "~/.config/nushell/env.nu"

[elvish.files]
"files/rc.elv" = "~/.config/elvish/rc.elv"

[lvim.files]
"files/lvim.lua" = "~/.config/lvim/config.lua"

[nvim.files]
"files/nvim" = {target="~/.config/nvim", type="symbolic", recurse=false}

[zsh.files]
"files/zshrc" = "~/.zshrc"

[bash.files]
"files/bashrc"="~/.bashrc"

[wezterm.files]
"files/wezterm.lua" = "C:\\Users\\Blue\\.config\\wezterm\\wezterm.lua"
[wezterm.variables]
font = "FantasqueSansMono NF"
font_size = 16.0
shell = "Powershell"
directory = "None"

[emacs.files]
"files/emacs.d" = {target="C:\\Users\\Blue\\.emacs.d", type="symbolic", recurse=false}
